backend:
  name: git-gateway
  branch: master
media_folder: 'static/img/'
public_folder: 'img'


collections:
  - name: news
    label: News 
    label_singular: News
    folder: 'content/news'
    path: '{{slug}}/index'
    slug: "{{year}}-{{month}}-{{title}}"
    filter: {field: "news", value: "news"}
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish this page on", name: "date", widget: "datetime"}
      - {label: "Summary", name: "summary", widget: "markdown"}
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}
  
  - name: pulication
    label: Publications
    label_singular: Publication
    folder: 'content/publication'
    path: '{{slug}}/index'  # Store talks in publication folder as "year-(First author last name)", e.g. `2019-Round`.
    slug: "{{year}}-{{last_name_first_author}}"
    identifier_field: slug
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Publication type", name: "publication_types", wiget: "hidden", default: "2"}
      - {label: "Title", name: "title", widget: "markdown", hint: "Use sentence case"}
      - {label: "Last name of the first author", name: "last_name_first_author", widget: "string", hint: "ex. Round"}
      - {label: "Article publishing date", name: "date", widget: "datetime", dateFormat: "YYYY-MM-DD", hint: "ex. 2020-11-25"}
      - {label: "Journal", name: "publication", widget: "string", hint: "Use standard ISO 4 journal abbreviations"}
      - {label: "Article DOI", name: "doi", widget: "string"}
      - label: "Authors"
        name: "author"
        widget: "list"
        field: {label: Name, name: author, widget: string, hint: Format = Firstname Lastname (ex. James Round)}
      - {label: "Abstract", name: "abstract", widget: "markdown"}

      
 
  - name: project
    label: Projects
    label_singular: Project
    folder: 'content/project'
    path: '{{slug}}/index'  # Store talks in project folder as "title".
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "markdown"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Publish this page on", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `featured.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}

  - name: team
    label: People  
    label_singular: People
    folder: 'content/team'
    path: '{{slug}}/index'
    slug: "{{firstname}}-{{lastname}}"
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "hidden", default: "{{firstname}} {{lastname}}"}
      - {label: "First name", name: "firstname", widget: "string"}
      - {label: "Last name", name: "lastname", widget: "string"}
      - label: "Role"
        name: "user_groups"
        widget: "select"
        options:
          - {label: "Researcher", value: "Researchers"}
          - {label: "Graduate student", value: "Graduate students"}       
          - {label: "Technician", value: "Technicians"}
          - {label: "Visitor", value: "Visitors"}
          - {label: "Alumni", value: "Alumni"}
      - label: "Postion"
        name: "role"
        widget: "select"
        options: ["Professor","Research associate", "Postdoctoral fellow", "PhD candidate", "PhD student", "MSc student", "Lab manager", "Technician"]
      - label: "Organization and department"
        name: organizations
        widget: "list"
        allow_add: false
        fields: 
          - label: "Insitution"
            name: "name"
            widget: "string"
            default: "University of British Columbia"
          - label: "Department"
            name: "name"
            widget: "string"
            default: "Microbiology and Immunology"
      - label: "Interests"
        name: "interests"
        widget: "list"
        allow_add: false
        fields: 
          - {label: "Intrest", name: "intrest1", widget: "string"}
          - {label: "Intrest", name: "intrest2", widget: "string"}
          - {label: "Intrest", name: "intrest3", widget: "string"}
      - label: "Education"
        name: education
        widget: "object"
        fields: 
          - label: "Education"
            name: "courses"
            widget: "list"
            allow_add: true
            fields: 
                        - label: "Degree"
                          name: "course"
                          widget: "string"
                          hint: "ex. PhD, Microbiology and Immunology"
                        - label: "Insitution"
                          name: "institution"
                          widget: "string"
                          hint: "ex. University of British Columbia"
                        - label: "Year of completion"
                          name: "year"
                          widget: "string"
                          hint: "ex. 2018"
      - {label: "Biography", name: "body", widget: "markdown"}
      - label: "Featured Image"
        name: "image"
        required: false
        widget: object
        fields:
          - label: "Upload an image named `avatar.jpg/png`"
            name: "filename"
            widget: "image"
            default: "featured"
            media_library:
              config:
                multiple: false
          - {label: Caption, name: caption, widget: string, required: false}
          - {label: Description for screen readers, name: alt_text, widget: string, required: false}
          - {label: "Where's the focal point in the image? Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.", name: focal_point, widget: string, required: false, default: "Smart"}
          - {label: Thumbnail Only?, name: preview_only, widget: boolean, default: false}

















  - name: homepage
    label: "Homepage"
    files:
      - file: "content/privacy.md"
        label: "Privacy Policy"
        name: "privacy"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Summary", name: "summary", widget: "markdown"}
          - label: "Draft"
            name: "draft"
            required: false
            widget: "boolean"
            default: false
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/terms.md"
        label: "Terms"
        name: "terms"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Summary", name: "summary", widget: "markdown"}
          - label: "Draft"
            name: "draft"
            required: false
            widget: "boolean"
            default: false
          - {label: "Body", name: "body", widget: "markdown"}
